app #13
front-end-by-rimantas/39-grupe-portfolio-react pull request #39
Opened 2022-07-25 13:04 UTC by AurimasCerniauskas

2022-07-25 14:39 UTC, DuudeXXI requested changes
Bendrai gerai, bet reikėtų kelis dalykus pataisyt, nes vis tiek ši sekcija nieko daugiau neturi ir prie jos negrįšim tai geriau iškarto pasidaryt iki galo:
- [ ] Reikia font-weight sumažint tiek p tiek h2
- [ ] patvarkyt collumn dydį sm į (col-sm-12 ml-sm-0)
- [ ] backgroundo užsklandą ant nuotraukos pakeist,nes dabar nublankina nuotrauką o reikia tokio labiau stiklo efekto, jeigu uždėjus juodą spalvą ir jos opacity sumažinus neišeina, greičiausiai reikės per fill arba filter uždėt užsklandą, filter man rodos kitaip apdirba nuotrauką, duoda efektus, tarkim grafinio dizaino spektre kai dedi juodą permatomą ji yra uždedama ant visų pixelių vienodai, o kai dedi per efektus, ją deda atitinkamai pagal efekto sąvybes, ekspeerimento principu reikia dėliot, mano spėjimas kol kas, kad reikia susirast brightness kintamąjį ir arba contrast, dar galimas variantas per HUE pabandyt, priklauso ką css duoda

2022-07-26 10:09 UTC, AurimasCerniauskas commented
pakoreguota

2022-07-26 10:17 UTC, DuudeXXI approved these changes

2022-07-26 11:25 UTC, Vital188 approved these changes

2022-07-27 06:35 UTC, Laimne approved these changes

2022-07-27 06:35 UTC, merged